<?php

function nestle_general_web_parts_theme($existing, $type, $theme, $path) {
  return array(
    'hello_block' => array(
      
	  #'render element' => 'elements',
      #'base hook' => 'block',
	  
      'template' => 'hello-block',
	  'variables' => array(
						'content' => NULL,
						'mydata' => NULL,
						'description' => t('This is dummy block content from my block Test.')
					),
    ),
	'page_footer_block' => array(
      'template' => 'page-footer-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'country_header_block' => array(
      'template' => 'country-header-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'city_header_block' => array(
      'template' => 'city-header-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'country_list_block' => array(
      'template' => 'country-list-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'two_col_city_block' => array(
      'template' => 'two-col-city-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'two_col_prods_block' => array(
      'template' => 'two-col-prods-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'three_col_prods_block' => array(
      'template' => 'three-col-prods-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'four_col_prods_block' => array(
      'template' => 'four-col-prods-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'products_detail_page_block' => array(
      'template' => 'products-detail-page-block',
	  'variables' => array( 'content' => NULL ),
    ),
	'home_page_header_block' => array(
      'template' => 'home-page-header-block',
	  'variables' => array( 'content' => NULL ),
    ),
  );
  
}